package view;

import model.*;
import controllers.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DARVIN
 */
public class frmCliente extends javax.swing.JInternalFrame {

    public JButton btn_edi = new JButton("Editar");
    int rown = -1;

    public frmCliente() {
        initComponents();
        idcli.setVisible(false);
        idcli1.setVisible(false);
        String valor1 = this.txtbusca.getText().trim();
        lis_cli(tbcli, valor1);

    }
    private boolean[] editable = {false, false, false, false, false, false};
    Cliente dao;

    public void lis_cli(JTable tabla, String valor) {

        tabla.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel dt = new DefaultTableModel(new String[]{"Id", "Apellidos", "Nombres", "DNI", "Telefono", "Selecciona"}, 0) {

            Class[] types = new Class[]{
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class,
                java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int row, int column) {
                return editable[column];
            }
        };
        btn_edi.setName("q");

        dao = new Cliente();
        mCliente vo = new mCliente();
        ArrayList<mCliente> list = dao.Lis_Cli(valor);
        if (list.size() > 0) {
            for (int i = 0; i < list.size(); i++) {
                Object fila[] = new Object[6];
                vo = list.get(i);
                fila[0] = vo.getIdcli();
                fila[1] = vo.getApecli();
                fila[2] = vo.getNomcli();
                fila[3] = vo.getDnicli();
                fila[4] = vo.getTelcli();
                fila[5] = btn_edi;
                dt.addRow(fila);
            }
        }
        tabla.setModel(dt);
        tabla.setRowHeight(20);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(7);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(80);
    }

    void accionNuevo() {
        txtapecli.setText("");
        txtnomcli.setText("");
        txttelcli.setText("");
        txtdnicli.setText("");
        idcli.setText("");
        idcli1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        idcli = new javax.swing.JLabel();
        txtbusca = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btnNue = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcli = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtapecli = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtnomcli = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtdnicli = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttelcli = new javax.swing.JTextField();
        idcli1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MANTENIMIENTO DE CLIENTES");
        addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                formCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jPanel1.setBackground(java.awt.Color.lightGray);

        idcli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        txtbusca.setToolTipText("");
        txtbusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscaKeyTyped(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnNue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnNue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/new_page.png"))); // NOI18N
        btnNue.setText("Nuevo");
        btnNue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNueActionPerformed(evt);
            }
        });

        tbcli.setBackground(new java.awt.Color(204, 204, 204));
        tbcli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbcli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbcli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcli);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(btnNue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNue)
                .addGap(119, 119, 119))
        );

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Apellidos");

        txtapecli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapecliActionPerformed(evt);
            }
        });
        txtapecli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtapecliKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapecliKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Nombres");

        txtnomcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomcliActionPerformed(evt);
            }
        });
        txtnomcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomcliKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnomcliKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Dni");

        txtdnicli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdnicliKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdnicliKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Telefono");

        txttelcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelcliActionPerformed(evt);
            }
        });
        txttelcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttelcliKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttelcliKeyTyped(evt);
            }
        });

        idcli1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 120, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdnicli, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txttelcli, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtbusca)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtapecli, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnomcli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(idcli1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(22, 22, 22)
                                .addComponent(idcli, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtapecli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdnicli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txttelcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(idcli, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idcli1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapecliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapecliKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtapecliKeyTyped

    private void txtbuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtbuscaKeyTyped

    private void btnNueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNueActionPerformed
        // TODO add your handling code here:
        accionNuevo();
        this.txtapecli.requestFocus();
    }//GEN-LAST:event_btnNueActionPerformed

    private void tbcliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcliMouseClicked
        // TODO add your handling code here:
        rown = tbcli.rowAtPoint(evt.getPoint());
        int column = tbcli.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tbcli.getRowHeight();
        int po = evt.getY();
        if (row < tbcli.getRowCount() && row >= 0 && column < tbcli.getColumnCount() && column >= 0) {
            Object value = tbcli.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equals("q")) {
                    try {
                        idcli1.setText("a");
                        idcli.setText(tbcli.getModel().getValueAt(rown, 0).toString());
                        txtapecli.setText(tbcli.getModel().getValueAt(rown, 1).toString());
                        txtnomcli.setText(tbcli.getModel().getValueAt(rown, 2).toString());
                        txtdnicli.setText(tbcli.getModel().getValueAt(rown, 3).toString());
                        txttelcli.setText(tbcli.getModel().getValueAt(rown, 4).toString());
                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                    }
                }
            }

        }

    }//GEN-LAST:event_tbcliMouseClicked

    private void formCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_formCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formCaretPositionChanged

    private void txtapecliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapecliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtnomcli.requestFocus();
        }
    }//GEN-LAST:event_txtapecliKeyPressed

    private void txtnomcliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomcliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txtdnicli.requestFocus();
        }
    }//GEN-LAST:event_txtnomcliKeyPressed

    private void txttelcliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelcliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtapecli.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ingresar apellidos");
                this.txtapecli.requestFocus();
                return;
            }
            if (txtnomcli.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ingresar nombre");
                this.txtnomcli.requestFocus();
                return;
            }
            if (txtdnicli.getText().isEmpty() || txtdnicli.getText().length() != 8) {
                JOptionPane.showMessageDialog(null, "ingresar dni");
                this.txtdnicli.requestFocus();
                return;
            }
            if (txttelcli.getText().isEmpty() || txttelcli.getText().length() != 9) {
                JOptionPane.showMessageDialog(null, "ingresar telefono");
                this.txttelcli.requestFocus();
                return;
            } else {
                mCliente sSql = new mCliente();
                Cliente cli = new Cliente();
                if (idcli1.getText().equals("a")) {
                    sSql.setApecli(txtapecli.getText());
                    sSql.setNomcli(txtnomcli.getText());
                    sSql.setDnicli(txtdnicli.getText());
                    sSql.setTelcli(txttelcli.getText());
                    sSql.setIdcli(Integer.parseInt(idcli.getText()));
                    cli.act_cli(sSql);
                    lis_cli(tbcli, txtbusca.getText());
                } else {
                    sSql.setApecli(txtapecli.getText());
                    sSql.setNomcli(txtnomcli.getText());
                    sSql.setDnicli(txtdnicli.getText().trim());
                    sSql.setTelcli(txttelcli.getText());
                    if (cli.verificadni(sSql).equals(txtdnicli.getText().trim())) {
                        JOptionPane.showMessageDialog(rootPane, "El cliente ya esta registrado");
                    } else {
                        cli.ins_cli(sSql);
                        mBidon sSql1 = new mBidon();
                        Bidon bid = new Bidon();
                        sSql1.setIdcli(1);
                        bid.ins_bid(sSql1);
                        lis_cli(tbcli, "");
                    }

                }
            }
        }
    }//GEN-LAST:event_txttelcliKeyPressed

    private void txttelcliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttelcliKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txttelcliKeyTyped

    private void txtnomcliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomcliKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtnomcliKeyTyped

    private void txtdnicliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdnicliKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txttelcli.requestFocus();
        }
    }//GEN-LAST:event_txtdnicliKeyPressed

    private void txtdnicliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdnicliKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdnicliKeyTyped

    private void txttelcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttelcliActionPerformed

    private void txtbuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String valor1 = this.txtbusca.getText().trim();
            lis_cli(tbcli, valor1);
            txtbusca.requestFocus();
            txtbusca.setSelectionStart(0);
            txtbusca.setSelectionEnd(txtbusca.getText().length());
        }
    }//GEN-LAST:event_txtbuscaKeyPressed

    private void txtapecliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapecliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapecliActionPerformed

    private void txtnomcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomcliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNue;
    private javax.swing.JLabel idcli;
    private javax.swing.JLabel idcli1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbcli;
    private javax.swing.JTextField txtapecli;
    private javax.swing.JTextField txtbusca;
    private javax.swing.JTextField txtdnicli;
    private javax.swing.JTextField txtnomcli;
    private javax.swing.JTextField txttelcli;
    // End of variables declaration//GEN-END:variables
}
