/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.Cliente;
import controllers.Com_Ven;
import controllers.Render;
import controllers.Vales;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.mCliente;
import model.mDetVal;
import model.mProducto;

/**
 *
 * @author DARVIN
 */
public class frmCom_Ven extends javax.swing.JInternalFrame {

    public JButton btn_env = new JButton("Enviar");
    int rown = -1;

    /**
     * Creates new form frmLisCli
     */
    public frmCom_Ven() {
        initComponents();
        lis_pro(tbpro, "");

    }

    private boolean[] editable = {false, false, false};
    Com_Ven dao;

    public void lis_pro(JTable tabla, String valor) {

        tabla.setDefaultRenderer(Object.class, new Render());
        DefaultTableModel dt = new DefaultTableModel(new String[]{"Id", "Producto", "Selecciona"}, 0) {

            Class[] types = new Class[]{
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int row, int column) {
                return editable[column];
            }
        };
        btn_env.setName("q");

        dao = new Com_Ven();
        mProducto vo = new mProducto();
        ArrayList<mProducto> list = dao.Lis_Pro(valor);
        if (list.size() > 0) {
            for (int i = 0; i < list.size(); i++) {
                Object fila[] = new Object[3];
                vo = list.get(i);
                fila[0] = vo.getIdpro();
                fila[1] = vo.getNompro();
                fila[2] = btn_env;
                dt.addRow(fila);
            }
        }
        tabla.setModel(dt);
        tabla.setRowHeight(20);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(7);
        tabla.getColumnModel().getColumn(1).setPreferredWidth(100);
        tabla.getColumnModel().getColumn(2).setPreferredWidth(80);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tfmini = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbmfin = new javax.swing.JLabel();
        lbmov = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpro = new javax.swing.JTable();
        rbcom = new javax.swing.JRadioButton();
        rbven = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        tfpre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tfcan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbpven = new javax.swing.JTable();
        tfpro = new javax.swing.JTextField();
        breg = new javax.swing.JButton();
        btcom = new javax.swing.JButton();
        btven = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tfmini1 = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("COMPRAS Y VENTAS");

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setToolTipText("");

        tfmini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfminiKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfminiKeyTyped(evt);
            }
        });

        jLabel1.setText("M.Inicial:");

        jLabel2.setText("Monto Finial:");

        lbmfin.setText("Monto Finial:");

        lbmov.setText("Monto Finial:");

        jLabel5.setText("Movimiento:");

        tbpro.setBackground(new java.awt.Color(204, 204, 204));
        tbpro.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbpro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Producto", "Accion"
            }
        ));
        jScrollPane1.setViewportView(tbpro);

        buttonGroup1.add(rbcom);
        rbcom.setText("Comprar");
        rbcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcomActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbven);
        rbven.setText("Vender");

        jLabel3.setText("Precio:");

        tfpre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpreActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad:");

        tbpven.setBackground(new java.awt.Color(204, 204, 204));
        tbpven.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbpven.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Producto", "Cantidad", "Precio", "Subtotal", "Accion"
            }
        ));
        jScrollPane2.setViewportView(tbpven);

        tfpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfproActionPerformed(evt);
            }
        });

        breg.setText("Registrar");

        btcom.setText("HisCompras");

        btven.setText("HisVentas");

        jLabel6.setText("Confirma:");

        tfmini1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfmini1ActionPerformed(evt);
            }
        });
        tfmini1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfmini1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfmini1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfmini, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(rbcom)
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(rbven)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfmini1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btven)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btcom)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbmfin)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbmov))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(tfpro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfcan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfpre, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(breg)
                .addGap(199, 199, 199))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfmini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(btcom)
                    .addComponent(btven)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfmini1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(lbmfin))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lbmov)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbcom, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbven))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tfpre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfpro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(breg)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbcomActionPerformed

    private void tfpreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpreActionPerformed

    private void tfproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfproActionPerformed

    private void tfmini1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfmini1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfmini1ActionPerformed

    private void tfminiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfminiKeyPressed
        // TODO add your handling code here
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.tfmini1.requestFocus();
        }
    }//GEN-LAST:event_tfminiKeyPressed

    private void tfminiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfminiKeyTyped
        // TODO add your handling code here
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_tfminiKeyTyped

    private void tfmini1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmini1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_tfmini1KeyTyped

    private void tfmini1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmini1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
             if (tfmini.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingresar monto");
                tfmini.requestFocus();
                return;
            }
            if (tfmini1.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Confirmar monto");
                tfmini1.requestFocus();
                return;
            }else{
            int mi1, mi2;
            mi1 = Integer.parseInt(tfmini.getText());
            mi2 = Integer.parseInt(tfmini1.getText());
            if (mi1 != mi2) {
                JOptionPane.showMessageDialog(null, "Confirmar monto");
                tfmini1.requestFocus();
                return;
            }
        }
        }
    }//GEN-LAST:event_tfmini1KeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton breg;
    private javax.swing.JButton btcom;
    private javax.swing.JButton btven;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbmfin;
    private javax.swing.JLabel lbmov;
    private javax.swing.JRadioButton rbcom;
    private javax.swing.JRadioButton rbven;
    public static javax.swing.JTable tbpro;
    public static javax.swing.JTable tbpven;
    private javax.swing.JTextField tfcan;
    private javax.swing.JTextField tfmini;
    private javax.swing.JTextField tfmini1;
    private javax.swing.JTextField tfpre;
    private javax.swing.JTextField tfpro;
    // End of variables declaration//GEN-END:variables
}
