/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import validaciones.Let_Num;
import model.*;
import controllers.*;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import validaciones.visualtabla;

/**
 *
 * @author DARVIN
 */
public class frmLisVal extends javax.swing.JInternalFrame {

    private final JComponent component = new JCheckBox();
    int rown = -1;
    Let_Num vallenu = new Let_Num();
    visualtabla vis_tab = new visualtabla();
    Vales val = new Vales();
    /**
     * Creates new form frmLisCli
     */
    //Tabla t = new Tabla();
    public frmLisVal() {
        initComponents();
        txtidven.setVisible(false);
        tabmes.setVisible(false);
        lbcodcli.setVisible(false);
        lbpre1.setVisible(false);
        lbpre2.setVisible(false);
        lbpre3.setVisible(false);
        txtcli.setEnabled(false);
        txtcodval.setEnabled(false);
        tfres.setEnabled(false);
        tfcan.setEnabled(false);
        cant_val_acu();

        // visualizar(tblisbol, "");
    }
    void val_cam() {
        txtvaldni.requestFocus();
        txtvaldni.setSelectionStart(0);
        txtvaldni.setSelectionEnd(txtvaldni.getText().length());
    }

    private void cant_val_acu() {
        try {
            double tot;
            tot = val.can_valcan() * 16;
            lbdin.setText("" + tot);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    void mostrar(String valor) {
        try {
            DefaultTableModel modelo;
            modelo = val.val_nofir(valor);
            this.tabmes.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    void tab_val_ent(String valor) {
        try {
            DefaultTableModel modelo;
            modelo = val.val_ent(valor);
            this.tbliscli.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    private void dat_pro() {
        mProducto mpro = new mProducto();
        ArrayList<mProducto> list = val.Dat_Pro("1");
        if (list.size() > 0) {
            for (int i = 0; i < list.size(); i++) {
                mpro = list.get(i);
                lbpre1.setText(""+mpro.getPre1());
                lbpre2.setText("" + mpro.getPre2());
                lbpre3.setText("" + mpro.getPre3());
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblisbol = new javax.swing.JTable();
        txtidven = new javax.swing.JLabel();
        txtvaldni = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbvalagr = new javax.swing.JTable();
        btnven = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabmes = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        cbomes = new javax.swing.JComboBox<>();
        cboano = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtcodval = new javax.swing.JTextField();
        lbcodcli = new javax.swing.JLabel();
        btnregpro1 = new javax.swing.JButton();
        txtcli = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbliscli = new javax.swing.JTable();
        btnregpro2 = new javax.swing.JButton();
        btnregpro3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbdin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfcan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jlgas = new javax.swing.JList<>();
        lbpre3 = new javax.swing.JLabel();
        lbpre2 = new javax.swing.JLabel();
        lbpre1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("MANTENIMIENTO DE VALES");

        jPanel1.setBackground(java.awt.Color.lightGray);

        tblisbol.setBackground(new java.awt.Color(153, 153, 153));
        tblisbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblisbol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblisbol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Codigo", "Fecha Vale", "Accion"
            }
        ));
        tblisbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblisbolMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblisbol);

        txtidven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        txtvaldni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtvaldniKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvaldniKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Ingresa DNI:");

        tbvalagr.setBackground(new java.awt.Color(153, 153, 153));
        tbvalagr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbvalagr.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbvalagr.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Fecha", "Accion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbvalagr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbvalagrMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbvalagr);

        btnven.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnven.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Save.png"))); // NOI18N
        btnven.setText("ENTREGAR");
        btnven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvenActionPerformed(evt);
            }
        });

        tabmes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Apellidos y Nombres", "DNI", "Codigo"
            }
        ));
        tabmes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmesMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabmes);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Fecha:");

        cbomes.setBackground(new java.awt.Color(255, 102, 0));
        cbomes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbomes.setForeground(new java.awt.Color(255, 0, 0));
        cbomes.setMaximumRowCount(13);
        cbomes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbomes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbomes.setPreferredSize(new java.awt.Dimension(80, 23));

        cboano.setBackground(new java.awt.Color(255, 102, 0));
        cboano.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboano.setForeground(new java.awt.Color(255, 0, 0));
        cboano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "anio", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        cboano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboanoMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Codigo de Vale:");

        txtcodval.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodvalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodvalKeyTyped(evt);
            }
        });

        lbcodcli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnregpro1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnregpro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Add.png"))); // NOI18N
        btnregpro1.setText("RegClientes");
        btnregpro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregpro1ActionPerformed(evt);
            }
        });

        txtcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcliActionPerformed(evt);
            }
        });

        tbliscli.setBackground(new java.awt.Color(204, 204, 204));
        tbliscli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbliscli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Fecha Vale", "Fecha entrega", "Responsable"
            }
        ));
        jScrollPane4.setViewportView(tbliscli);

        btnregpro2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnregpro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Guardar1.JPG"))); // NOI18N
        btnregpro2.setText("Bidones");
        btnregpro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregpro2ActionPerformed(evt);
            }
        });

        btnregpro3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnregpro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/Save.png"))); // NOI18N
        btnregpro3.setText("No Canjeados");
        btnregpro3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregpro3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Dinero en juego:");

        lbdin.setText("jLabel2");

        jLabel2.setText("Responsable:");

        tfres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfresKeyTyped(evt);
            }
        });

        jLabel5.setText("Cantidad:");

        tfcan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfcanKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfcanKeyTyped(evt);
            }
        });

        jLabel7.setText("Gas:");

        jScrollPane5.setViewportView(jlgas);

        lbpre3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbpre2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbpre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtvaldni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtidven, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnven)
                                .addGap(39, 39, 39)
                                .addComponent(lbpre1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbpre2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbpre3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbcodcli, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfres, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfcan, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtcodval, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnregpro2)
                                .addGap(18, 18, 18)
                                .addComponent(btnregpro1)
                                .addGap(18, 18, 18)
                                .addComponent(btnregpro3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cbomes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cboano, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtcli, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbdin, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtvaldni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtidven, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnven, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbcodcli, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbpre3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbpre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbpre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(cbomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cboano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtcodval, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnregpro3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnregpro1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnregpro2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfcan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbdin))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtvaldniKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvaldniKeyTyped
        // TODO add your handling code here:
        vallenu.solonum(evt);
        
    }//GEN-LAST:event_txtvaldniKeyTyped

    private void txtvaldniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvaldniKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String valor1 = this.txtvaldni.getText().trim();
            vis_tab.val_no_fir(tabmes, valor1);
            vis_tab.val_acu(tblisbol, valor1);
            tab_val_ent(valor1);
            val_cam();
            tabmes.setVisible(true);
            txtvaldni.requestFocus();
            txtvaldni.setSelectionStart(0);
            txtvaldni.setSelectionEnd(txtvaldni.getText().length());
            txtcli.setText(val.rec_apenom(valor1));
            txtcli.setDisabledTextColor(Color.blue);
            lbcodcli.setText(val.rec_codcli(valor1));

            if (txtcli.getText().length() < 2) {
                txtvaldni.requestFocus();
            } else {
                txtcodval.requestFocus(true);
                txtcodval.setEnabled(true);
            }

        }
    }//GEN-LAST:event_txtvaldniKeyPressed

    private void tblisbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblisbolMouseClicked

        rown = tblisbol.rowAtPoint(evt.getPoint());
        int column = tblisbol.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblisbol.getRowHeight();
        int po = evt.getY();
        if (row < tblisbol.getRowCount() && row >= 0 && column < tblisbol.getColumnCount() && column >= 0) {
            Object value = tblisbol.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                String cod = "" + tblisbol.getValueAt(rown, 0);
                String fec = "" + tblisbol.getValueAt(rown, 2);
                if (boton.getName().equals("q")) {
                    try {
                        int conta = tbvalagr.getRowCount();
                        if (conta > 2) {
                            JOptionPane.showMessageDialog(rootPane, "Agrega 3 vales como maximo");
                            return;
                        }
                        vis_tab.val_agr(tbvalagr, cod, fec);
                        tfres.setEnabled(true);
                        tfcan.setEnabled(true);
                        tfres.requestFocus();
                    } catch (HeadlessException ex) {
                        System.out.println(ex.getMessage());
                    }
                }
            }

        }

    }//GEN-LAST:event_tblisbolMouseClicked

    private void tbvalagrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbvalagrMouseClicked
        // TODO add your handling code here:
        vis_tab.qui_fila(tbvalagr, evt);
    }//GEN-LAST:event_tbvalagrMouseClicked

    private void btnvenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvenActionPerformed
        // TODO add your handling code here:
        int numfil = frmLisVal.tbvalagr.getRowCount();
        if (numfil == 0) {
            JOptionPane.showMessageDialog(rootPane, "No ha agregado ningun vale");
            return;
        }
        if (tfres.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese responsable");
            tfres.requestFocus();
            return;
        }
        
        if (tfcan.getText().isEmpty() || tfcan.getText().equals(0) ) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese cantidad");
            tfcan.requestFocus();  
            return;
        }
        int can=Integer.parseInt(tfcan.getText());
        if (can >3) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese cantidad");
            tfcan.requestFocus();  
            return;
        }
        
        if (jlgas.isSelectedIndex(0)) {
            JOptionPane.showMessageDialog(rootPane, "Selecciona gas ");
            jlgas.requestFocus();
            
        } else {
            dat_pro();
            int cangas = Integer.parseInt(tfcan.getText());
            double monto;
            int pre1=Integer.parseInt(lbpre1.getText());
            int pre2=Integer.parseInt(lbpre2.getText());
            int pre3=Integer.parseInt(lbpre3.getText());
            if(numfil==1 && cangas==1){
                monto=pre1;
                return;
            }
            if(numfil==2 && cangas==1){
                monto=pre2;
                return;
            }
            if(numfil==3 && cangas==1){
                monto=pre3;
                return;
            }
            if(numfil==3 && cangas==2){
                monto=30;
                return;
            }
            if(numfil==2 && cangas==2){
                monto=pre1*cangas;
                return;
            }
            if(numfil==3 && cangas==3){
                monto=pre1*cangas;
                return;
            }
            mDetVal mval = new mDetVal();
            for (int i = 0; i < frmLisVal.tbvalagr.getRowCount(); i++) {
                LocalDate localDate = LocalDate.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy");
                String fec = localDate.format(formatter);
                mval.setFecdetval(fec);
                mval.setEstdetval("2");
                mval.setResponsable(tfres.getText());
                mval.setIddetval(Integer.parseInt(tbvalagr.getValueAt(i, 0).toString()));
                val.act_valfir(mval);
            }

            vis_tab.lim_tabla(tbvalagr);
            vis_tab.val_acu(tblisbol, txtvaldni.getText());
            val_cam();
            tab_val_ent(txtvaldni.getText());
            txtvaldni.requestFocus();
            txtvaldni.setSelectionStart(0);
            txtvaldni.setSelectionEnd(txtvaldni.getText().length());
            tfres.setText("");
            tfcan.setText("");
            jlgas.setSelectedIndex(0);

        }
    }//GEN-LAST:event_btnvenActionPerformed

    private void txtcodvalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodvalKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtcodval.getText().length() == 0 || txtcodval.getText().equals(0) || txtcodval.getText().length() != 13) {
                JOptionPane.showMessageDialog(null, "ingresar codigo");
                txtcodval.requestFocus();
                return;
            }
            if (cbomes.getSelectedIndex() == 0 || cboano.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "ingresar fecha");
            } else {
                mDetVal mval = new mDetVal();
                mval.setMesvale(cbomes.getSelectedIndex());
                mval.setAnovale(cboano.getSelectedItem().toString());
                mval.setIdcli(Integer.parseInt(lbcodcli.getText()));
                if (val.ver_vale(mval).equals("")) {
                    mval.setIdcli(Integer.parseInt(lbcodcli.getText()));
                    mval.setCoddetval(txtcodval.getText());
                    mval.setEstdetval("0");
                    mval.setMesvale(cbomes.getSelectedIndex());
                    mval.setAnovale(cboano.getSelectedItem().toString());
                    val.ins_detval(mval);
                    txtvaldni.requestFocus();
                    txtvaldni.setSelectionStart(0);
                    txtvaldni.setSelectionEnd(txtvaldni.getText().length());
                    vis_tab.val_no_fir(tabmes, txtvaldni.getText());
                    txtcodval.setText("");
                    txtcli.setText("");
                    txtcodval.setEnabled(false);
                } else {
                    JOptionPane.showMessageDialog(rootPane, "El cliente ya es beneficiario");
                    txtvaldni.requestFocus();
                    txtvaldni.setSelectionStart(0);
                    txtvaldni.setSelectionEnd(txtvaldni.getText().length());
                }

            }
        }
    }//GEN-LAST:event_txtcodvalKeyPressed

    private void txtcodvalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodvalKeyTyped
        // TODO add your handling code here:
        vallenu.solonum(evt);
    }//GEN-LAST:event_txtcodvalKeyTyped

    private void btnregpro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregpro1ActionPerformed
        // TODO add your handling code here:
        frmCliente pro = new frmCliente();
        frmPrincipal.panfer.add(pro);
        pro.toFront();
        pro.setVisible(true);
    }//GEN-LAST:event_btnregpro1ActionPerformed

    private void txtcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcliActionPerformed

    private void btnregpro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregpro2ActionPerformed
        // TODO add your handling code here:
        frmManBid pro = new frmManBid();
        frmPrincipal.panfer.add(pro);
        pro.toFront();
        pro.setVisible(true);
    }//GEN-LAST:event_btnregpro2ActionPerformed

    private void cboanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboanoMouseClicked
        // TODO add your handling code here:
        if (cboano.getSelectedIndex() > 0) {
            txtcodval.requestFocus();
        }
    }//GEN-LAST:event_cboanoMouseClicked

    private void tabmesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmesMouseClicked
        // TODO add your handling code here:
        rown = tabmes.rowAtPoint(evt.getPoint());
        int column = tabmes.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabmes.getRowHeight();
        int po = evt.getY();
        if (row < tabmes.getRowCount() && row >= 0 && column < tabmes.getColumnCount() && column >= 0) {
            Object value = tabmes.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                String va1 = "" + tabmes.getValueAt(rown, 0);
                String va2 = "" + tabmes.getValueAt(rown, 2);
                if (boton.getName().equals("q1")) {
                    try {
                        int YesOrNo = JOptionPane.showConfirmDialog(null, "Estas seguro que firmó", "confirma el mensaje", JOptionPane.YES_NO_OPTION);
                        if (YesOrNo == 0) {
                            mDetVal mval = new mDetVal();
                            mval.setIddetval(Integer.parseInt("" + tabmes.getValueAt(rown, 0)));
                            mval.setEstdetval("1");
                            val.act_valnofir(mval);
                            vis_tab.val_no_fir(tabmes, txtvaldni.getText());
                            vis_tab.val_acu(tblisbol, txtvaldni.getText());
                            val_cam();
                            cant_val_acu();
                        }
                    } catch (HeadlessException | NumberFormatException ex) {
                        System.out.println(ex.getMessage());
                    }
                }
            }

        }
    }//GEN-LAST:event_tabmesMouseClicked

    private void btnregpro3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregpro3ActionPerformed
        // TODO add your handling code here:
        frmNoCan pro = new frmNoCan();
        frmPrincipal.panfer.add(pro);
        pro.toFront();
        pro.setVisible(true);
    }//GEN-LAST:event_btnregpro3ActionPerformed

    private void tfresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfresKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tfcan.requestFocus();
        }
    }//GEN-LAST:event_tfresKeyPressed

    private void tfresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfresKeyTyped
        // TODO add your handling code here:

        vallenu.sololet(evt);

    }//GEN-LAST:event_tfresKeyTyped

    private void tfcanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcanKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jlgas.requestFocus();
        }
    }//GEN-LAST:event_tfcanKeyPressed

    private void tfcanKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfcanKeyTyped
        // TODO add your handling code here:
        vallenu.solonum(evt);
    }//GEN-LAST:event_tfcanKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnregpro1;
    private javax.swing.JButton btnregpro2;
    private javax.swing.JButton btnregpro3;
    private javax.swing.JButton btnven;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboano;
    private javax.swing.JComboBox<String> cbomes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> jlgas;
    private javax.swing.JLabel lbcodcli;
    private javax.swing.JLabel lbdin;
    private javax.swing.JLabel lbpre1;
    private javax.swing.JLabel lbpre2;
    private javax.swing.JLabel lbpre3;
    private javax.swing.JTable tabmes;
    public static javax.swing.JTable tblisbol;
    private javax.swing.JTable tbliscli;
    public static javax.swing.JTable tbvalagr;
    private javax.swing.JTextField tfcan;
    private javax.swing.JTextField tfres;
    private javax.swing.JTextField txtcli;
    public static javax.swing.JTextField txtcodval;
    private javax.swing.JLabel txtidven;
    private javax.swing.JTextField txtvaldni;
    // End of variables declaration//GEN-END:variables
}
