/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.*;
import controllers.*;
import com.mysql.jdbc.Connection;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DARVIN
 */
public class frmManBid extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmLisCli
     */
    public frmManBid() {
        initComponents();
        mostrar("");
        mostrar1("");
        popmenven();
         popmenven1();
        combosde();
        txtidven.setVisible(false);
        txtcli1.setEnabled(false);
        btnEnt.setEnabled(false);
        cbonumbid.setEnabled(false);
         txtcli1.setDisabledTextColor(Color.blue);
    }

    void mostrar(String valor) {
        try {
            DefaultTableModel modelo;
            Cliente cat = new Cliente();
            modelo = cat.datoslocos(valor);
            this.tblisbol.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
void mostrar1(String valor) {
        try {
            DefaultTableModel modelo;
            Cliente cat = new Cliente();
            modelo = cat.datos2(valor);
            this.tblisbol1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    void combosde() {
        try {
            Date fec = new Date();
            int mes = fec.getMonth() + 1;
            int an = fec.getYear() + 1900;
            String an1 = Integer.toString(an);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    void popmenven() {
        JPopupMenu popupmenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Enviar");
        menuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int col = tblisbol.getSelectedRow();

                if (col == -1) {
                    JOptionPane.showMessageDialog(null, "selecciona una dato");
                } else {
                    txtcli1.setText(tblisbol.getValueAt(col, 1).toString() + " " + tblisbol.getValueAt(col, 2).toString());
                    txtidven.setText(tblisbol.getValueAt(col, 0).toString());
                    btnEnt.setEnabled(true);
                    cbonumbid.setEnabled(true);
                }

            }
        });

        popupmenu.add(menuItem1);

        tblisbol.setComponentPopupMenu(popupmenu);
    }
       void popmenven1() {
        JPopupMenu popupmenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Recepcionar");
        menuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int col = tblisbol1.getSelectedRow();

                if (col == -1) {
                    JOptionPane.showMessageDialog(null, "selecciona una dato");
                } else {
                    int YesOrNo = JOptionPane.showConfirmDialog(null, "Estas seguro de recepcionar bidon(es)", "confirma el mensaje", JOptionPane.YES_NO_OPTION);
        if (YesOrNo == 0) {
            mBidon sSql = new mBidon();
            Bidon ven = new Bidon();
            SimpleDateFormat formateador = new SimpleDateFormat(
                    "dd 'de' MMMM 'de' yyyy", new Locale("ES"));
            Date fechaDate = new Date();
            String fec = formateador.format(fechaDate);
            sSql.setIdcli(Integer.parseInt(tblisbol1.getModel().getValueAt(col, 0).toString()));
            sSql.setFecalmbid(fec);
            sSql.setEstbid(Integer.parseInt(tblisbol1.getModel().getValueAt(col, 4).toString()));
            if (ven.actualizarbid(sSql)) {
                mostrar1("");
                txtidven.setText("");
               
            }
        }
                }

            }
        });

        popupmenu.add(menuItem1);

        tblisbol1.setComponentPopupMenu(popupmenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblisbol = new javax.swing.JTable();
        txtidven = new javax.swing.JLabel();
        txtcli1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnEnt = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbonumbid = new javax.swing.JComboBox<>();
        eticod1 = new javax.swing.JLabel();
        txtbusca = new javax.swing.JTextField();
        eticod2 = new javax.swing.JLabel();
        txtbusca1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblisbol1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MANTENIMIENTO DE ENCARGO DE BIDONES");

        jPanel1.setBackground(java.awt.Color.lightGray);

        tblisbol.setBackground(new java.awt.Color(153, 153, 153));
        tblisbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblisbol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblisbol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblisbol);

        txtidven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        txtcli1.setForeground(new java.awt.Color(0, 0, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("encarga");

        btnEnt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnEnt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Imagenes/search.png"))); // NOI18N
        btnEnt.setText("Registrar");
        btnEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Señor:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("bidon(es)");

        cbonumbid.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        cbonumbid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));

        eticod1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        eticod1.setText("Ingrese Apellidos:");

        txtbusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscaKeyTyped(evt);
            }
        });

        eticod2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        eticod2.setText("Ingrese Apellidos:");

        txtbusca1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbusca1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbusca1KeyTyped(evt);
            }
        });

        tblisbol1.setBackground(new java.awt.Color(153, 153, 153));
        tblisbol1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblisbol1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblisbol1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblisbol1);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("Encargo de Bidones");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Bidones encargados");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtcli1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbonumbid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEnt))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(eticod2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtbusca1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(eticod1)
                        .addGap(18, 18, 18)
                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtidven, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eticod1)
                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtidven, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(cbonumbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnEnt))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eticod2)
                    .addComponent(txtbusca1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Estas seguro que te encargan "+cbonumbid.getSelectedItem().toString()+" bidon(es)", "confirma el mensaje", JOptionPane.YES_NO_OPTION);
        if (YesOrNo == 0) {
            mBidon sSql = new mBidon();
            Bidon ven = new Bidon();
            SimpleDateFormat formateador = new SimpleDateFormat(
                    "dd 'de' MMMM 'de' yyyy", new Locale("ES"));
            Date fechaDate = new Date();
            String fec = formateador.format(fechaDate);
            sSql.setIdcli(Integer.parseInt(txtidven.getText()));
            sSql.setFecencbid(fec);
            sSql.setEstbid(Integer.parseInt(cbonumbid.getSelectedItem().toString()));
            if (ven.actualizar(sSql) == true) {
                mostrar1("");
                txtcli1.setEnabled(false);
                txtcli1.setText("");
                txtidven.setText("");
                btnEnt.setEnabled(false);
                cbonumbid.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnEntActionPerformed

    private void txtbuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtbuscaKeyTyped

    private void txtbuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        mostrar(this.txtbusca.getText().trim());
         txtbusca.requestFocus();
        txtbusca.setSelectionStart(0);
        txtbusca.setSelectionEnd(txtbusca.getText().length());}
    }//GEN-LAST:event_txtbuscaKeyPressed

    private void txtbusca1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusca1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            mostrar1(txtbusca1.getText().trim());
        txtbusca1.requestFocus();
        txtbusca1.setSelectionStart(0);
        txtbusca1.setSelectionEnd(txtbusca1.getText().length());}
    }//GEN-LAST:event_txtbusca1KeyPressed

    private void txtbusca1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusca1KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(c < '0' || c > '9')) {
            evt.consume();
        }
    }//GEN-LAST:event_txtbusca1KeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbonumbid;
    private javax.swing.JLabel eticod1;
    private javax.swing.JLabel eticod2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblisbol;
    private javax.swing.JTable tblisbol1;
    private javax.swing.JTextField txtbusca;
    private javax.swing.JTextField txtbusca1;
    private javax.swing.JTextField txtcli1;
    private javax.swing.JLabel txtidven;
    // End of variables declaration//GEN-END:variables
}
