/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import validaciones.Let_Num;
import model.*;
import controllers.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import validaciones.visualtabla;

/**
 *
 * @author DARVIN
 */
public class frmManBid extends javax.swing.JInternalFrame {

    int rown = -1;
    Let_Num vallenu = new Let_Num();
    visualtabla v1 = new visualtabla();

    /**
     * Creates new form frmLisCli
     */
    public frmManBid() {
        initComponents();
        v1.lis_no_can(tblisbol, "");

        mostrar1("");
        popmenven1();
        txtidven.setVisible(false);
        idcli.setVisible(false);
        canbid.setEnabled(false);
    }

    void mostrar1(String valor) {
        try {
            DefaultTableModel modelo;
            Bidon cat = new Bidon();
            modelo = cat.bid_enc(valor);
            this.tblisbol1.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    void popmenven1() {
        JPopupMenu popupmenu = new JPopupMenu();
        JMenuItem menuItem1 = new JMenuItem("Recepcionar");
        menuItem1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int col = tblisbol1.getSelectedRow();
                if (col == -1) {
                    JOptionPane.showMessageDialog(null, "selecciona una dato");
                } else {

                    mBidon sSql = new mBidon();
                    Bidon ven = new Bidon();
                    LocalDate localDate = LocalDate.now();
                    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy");
                    String fec = localDate.format(formatter);
                    sSql.setIdcli(Integer.parseInt(tblisbol1.getModel().getValueAt(col, 0).toString()));
                    sSql.setFecalmbid(fec);
                    sSql.setCanbid(Integer.parseInt(tblisbol1.getModel().getValueAt(col, 4).toString()));
                    if (ven.rec_bid(sSql)) {
                        mostrar1("");
                        txtidven.setText("");

                    }
                }
            }

        });

        popupmenu.add(menuItem1);

        tblisbol1.setComponentPopupMenu(popupmenu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblisbol = new javax.swing.JTable();
        txtidven = new javax.swing.JLabel();
        eticod1 = new javax.swing.JLabel();
        txtbusca = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblisbol1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        canbid = new javax.swing.JTextField();
        eticod2 = new javax.swing.JLabel();
        idcli = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MANTENIMIENTO DE ENCARGO DE BIDONES");

        jPanel1.setBackground(java.awt.Color.lightGray);

        tblisbol.setBackground(new java.awt.Color(153, 153, 153));
        tblisbol.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblisbol.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblisbol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblisbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblisbolMouseClicked(evt);
            }
        });
        tblisbol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblisbolKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tblisbol);

        txtidven.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        eticod1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        eticod1.setText("Apellidos:");

        txtbusca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbuscaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscaKeyTyped(evt);
            }
        });

        tblisbol1.setBackground(new java.awt.Color(153, 153, 153));
        tblisbol1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblisbol1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tblisbol1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblisbol1);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 0));
        jLabel9.setText("Bidones encargados");

        canbid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                canbidKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                canbidKeyTyped(evt);
            }
        });

        eticod2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        eticod2.setText("Cantidad:");

        idcli.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eticod1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtidven, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(138, 138, 138))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(eticod2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(canbid, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idcli, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(eticod1)
                        .addComponent(txtbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtidven, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(canbid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eticod2))
                    .addComponent(idcli, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyTyped
        // TODO add your handling code here:
        vallenu.sololet(evt);
    }//GEN-LAST:event_txtbuscaKeyTyped

    private void txtbuscaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            v1.lis_no_can(tblisbol, txtbusca.getText());
            mostrar1(txtbusca.getText());
            txtbusca.requestFocus();
            txtbusca.setSelectionStart(0);
            txtbusca.setSelectionEnd(txtbusca.getText().length());
        }
    }//GEN-LAST:event_txtbuscaKeyPressed

    private void canbidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_canbidKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (canbid.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ingresar cantidad");
                this.canbid.requestFocus();
                return;
            } else {
                mBidon sSql = new mBidon();
                Bidon ven = new Bidon();
                LocalDate localDate = LocalDate.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd 'de' MMMM 'de' yyyy");
                String fec = localDate.format(formatter);
                sSql.setIdcli(Integer.parseInt(idcli.getText()));
                sSql.setFecencbid(fec);
                sSql.setCanbid(Integer.parseInt(canbid.getText()));
                canbid.setEnabled(false);
                ven.enc_bid(sSql);
                mostrar1("");
                canbid.setText("");

            }
        }


    }//GEN-LAST:event_canbidKeyPressed

    private void canbidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_canbidKeyTyped
        // TODO add your handling code here:

        vallenu.solonum(evt);
    }//GEN-LAST:event_canbidKeyTyped

    private void tblisbolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblisbolKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_tblisbolKeyPressed

    private void tblisbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblisbolMouseClicked
        // TODO add your handling code here:
        rown = tblisbol.rowAtPoint(evt.getPoint());
        int column = tblisbol.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tblisbol.getRowHeight();
        int po = evt.getY();
        if (row < tblisbol.getRowCount() && row >= 0 && column < tblisbol.getColumnCount() && column >= 0) {
            Object value = tblisbol.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                String va1 = "" + tblisbol.getValueAt(rown, 0);

                if (boton.getName().equals("q")) {
                    try {
                        canbid.setEnabled(true);
                        idcli.setText(va1);
                        canbid.requestFocus();

                    } catch (Exception ex) {
                        System.out.println(ex.getMessage());
                    }
                }
            }

        }
    }//GEN-LAST:event_tblisbolMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField canbid;
    private javax.swing.JLabel eticod1;
    private javax.swing.JLabel eticod2;
    private javax.swing.JLabel idcli;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblisbol;
    private javax.swing.JTable tblisbol1;
    private javax.swing.JTextField txtbusca;
    private javax.swing.JLabel txtidven;
    // End of variables declaration//GEN-END:variables
}
