/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import validaciones.Let_Num;
import controllers.Vales;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.mDetVal;

/**
 *
 * @author DARVIN
 */
public class frmNoCan extends javax.swing.JInternalFrame {
Let_Num vallenu = new Let_Num();
    /**
     * Creates new form frmLisCli
     */
    public frmNoCan() {
        initComponents();

    }

    void mostrar() {
        try {
            DefaultTableModel modelo;
            Vales clilis = new Vales();
            mDetVal md = new mDetVal();
            md.setMesvale(Integer.parseInt(tfmes.getText()));
            md.setAnovale(tfano.getText());
            modelo = clilis.no_can(md);
            tbliscli.setModel(modelo);
            tbliscli.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbliscli.getColumnModel().getColumn(1).setPreferredWidth(300);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbliscli = new javax.swing.JTable();
        btnent = new javax.swing.JButton();
        tfano = new javax.swing.JTextField();
        tfmes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CLIENTES");

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setToolTipText("");

        tbliscli.setBackground(new java.awt.Color(204, 204, 204));
        tbliscli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbliscli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Apellidos y Nombres"
            }
        ));
        jScrollPane1.setViewportView(tbliscli);
        if (tbliscli.getColumnModel().getColumnCount() > 0) {
            tbliscli.getColumnModel().getColumn(0).setResizable(false);
            tbliscli.getColumnModel().getColumn(0).setPreferredWidth(10);
            tbliscli.getColumnModel().getColumn(1).setResizable(false);
            tbliscli.getColumnModel().getColumn(1).setPreferredWidth(300);
        }

        btnent.setText("Validar");
        btnent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentActionPerformed(evt);
            }
        });

        tfano.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfanoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfanoKeyTyped(evt);
            }
        });

        tfmes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfmesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfmesKeyTyped(evt);
            }
        });

        jLabel1.setText("Mes:");

        jLabel2.setText("Año:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfmes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfano, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnent)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnent)
                    .addComponent(tfano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Estas seguro de regular", "confirma el mensaje", JOptionPane.YES_NO_OPTION);
        if (YesOrNo == 0) {
            for (int i = 0; i < frmNoCan.tbliscli.getRowCount(); i++) {
                mDetVal Sql = new mDetVal();
                Vales emp = new Vales();
                SimpleDateFormat formateador = new SimpleDateFormat(
                        "dd 'de' MMMM 'de' yyyy", new Locale("ES"));
                Date fechaDate = new Date();
                String fec = formateador.format(fechaDate);
                Sql.setResponsable("nc");
                Sql.setFecdetval(fec);
                Sql.setEstdetval("2");
                Sql.setIddetval(Integer.parseInt(tbliscli.getValueAt(i, 0).toString()));
                emp.act_valnocan(Sql);

            }
            mostrar();
        }
    }//GEN-LAST:event_btnentActionPerformed

    private void tfmesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmesKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.tfano.requestFocus();
        }
    }//GEN-LAST:event_tfmesKeyPressed

    private void tfanoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfanoKeyPressed
        // TODO add your handling code here: 
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           mostrar();
        }
    }//GEN-LAST:event_tfanoKeyPressed

    private void tfmesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfmesKeyTyped
        // TODO add your handling code here:
        vallenu.solonum(evt);
    }//GEN-LAST:event_tfmesKeyTyped

    private void tfanoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfanoKeyTyped
        // TODO add your handling code here:
        vallenu.solonum(evt);
    }//GEN-LAST:event_tfanoKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbliscli;
    private javax.swing.JTextField tfano;
    private javax.swing.JTextField tfmes;
    // End of variables declaration//GEN-END:variables
}
