/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controllers.Cliente;
import controllers.Vales;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;
import model.mDetVal;

/**
 *
 * @author DARVIN
 */
public class frmNoCan extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmLisCli
     */
    public frmNoCan() {
        initComponents();

    }

    void mostrar() {
        try {
            DefaultTableModel modelo;
            Vales clilis = new Vales();
            mDetVal md = new mDetVal();
            md.setMesvale(cbomes.getSelectedIndex());
            md.setAnovale(cboano.getSelectedItem().toString());
            md.setFirma(0);
            modelo = clilis.datnocan(md);
            this.tbliscli.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbliscli = new javax.swing.JTable();
        cbomes = new javax.swing.JComboBox<>();
        cboano = new javax.swing.JComboBox<>();
        btnent = new javax.swing.JButton();
        btnbus1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CLIENTES");

        jPanel1.setBackground(java.awt.Color.lightGray);
        jPanel1.setToolTipText("");

        tbliscli.setBackground(new java.awt.Color(204, 204, 204));
        tbliscli.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tbliscli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Apellidos y Nombres"
            }
        ));
        jScrollPane1.setViewportView(tbliscli);

        cbomes.setBackground(new java.awt.Color(255, 102, 0));
        cbomes.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cbomes.setForeground(new java.awt.Color(255, 0, 0));
        cbomes.setMaximumRowCount(13);
        cbomes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        cbomes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbomes.setPreferredSize(new java.awt.Dimension(80, 23));

        cboano.setBackground(new java.awt.Color(255, 102, 0));
        cboano.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cboano.setForeground(new java.awt.Color(255, 0, 0));
        cboano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "anio", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        cboano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboanoMouseClicked(evt);
            }
        });

        btnent.setText("Validar");
        btnent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnentActionPerformed(evt);
            }
        });

        btnbus1.setText("Buscar");
        btnbus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbus1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbomes, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cboano, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btnbus1)
                        .addGap(270, 270, 270)
                        .addComponent(btnent))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnent)
                    .addComponent(btnbus1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboanoMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_cboanoMouseClicked

    private void btnbus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbus1ActionPerformed
        // TODO add your handling code here:
        if (cbomes.getSelectedIndex() == 0 || cboano.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Ingresar fecha");
            return;
        } else {
            mostrar();
        }
    }//GEN-LAST:event_btnbus1ActionPerformed

    private void btnentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnentActionPerformed
        // TODO add your handling code here:
        int YesOrNo = JOptionPane.showConfirmDialog(null, "Estas seguro de regular", "confirma el mensaje", JOptionPane.YES_NO_OPTION);
        if (YesOrNo == 0) {
        for (int i = 0; i < frmNoCan.tbliscli.getRowCount(); i++) {
        mDetVal Sql = new mDetVal();
        Vales emp = new Vales();
        SimpleDateFormat formateador = new SimpleDateFormat(
                "dd 'de' MMMM 'de' yyyy", new Locale("ES"));
        Date fechaDate = new Date();
        String fec = formateador.format(fechaDate);
        Sql.setResponsable("nc");
        Sql.setFecdetval(fec);
        Sql.setEstdetval("0");
        Sql.setFirma(1);
        Sql.setIddetval(Integer.parseInt(tbliscli.getValueAt(i, 0).toString()));
        emp.actvalpen(Sql);
         
        }
        mostrar();
    }
    }//GEN-LAST:event_btnentActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbus1;
    private javax.swing.JButton btnent;
    private javax.swing.JComboBox<String> cboano;
    private javax.swing.JComboBox<String> cbomes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tbliscli;
    // End of variables declaration//GEN-END:variables
}
